namespace: control-plane
storageClass: standard
prometheusOperator:
  tolerations: []
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 500Mi
grafana:
  service:
    type: ClusterIP
    nodePort: 30000
  tolerations: []
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 400Mi
  persistence:
    resources:
      requests:
        storage: 5Gi
supernodeDashboard:
  service:
    type: ClusterIP
    nodePort: 30001
  tolerations: []
  resources:
    limits:
      cpu: 2000m
      memory: 400Mi
    requests:
      cpu: 500m
      memory: 400Mi
prometheus:
  tolerations: []
  resources:
    requests:
      memory: 400Mi
  storage:
    resources:
      requests:
        storage: 40Gi
