{{- $fullName := include "dolos.fullname" . -}}
{{- $svcType := default "ClusterIP" .Values.service.type -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dolos.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svcType }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  selector:
{{- include "dolos.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      {{- if and (or (eq $svcType "NodePort") (eq $svcType "LoadBalancer")) .Values.service.grpcNodePort }}
      nodePort: {{ .Values.service.grpcNodePort }}
      {{- end }}
    - name: ouroboros
      port: {{ .Values.service.ouroborosPort }}
      targetPort: ouroboros
      protocol: TCP
      {{- if and (or (eq $svcType "NodePort") (eq $svcType "LoadBalancer")) .Values.service.ouroborosNodePort }}
      nodePort: {{ .Values.service.ouroborosNodePort }}
      {{- end }}
    - name: minibf
      port: {{ .Values.service.minibfPort }}
      targetPort: minibf
      protocol: TCP
      {{- if and (or (eq $svcType "NodePort") (eq $svcType "LoadBalancer")) .Values.service.minibfNodePort }}
      nodePort: {{ .Values.service.minibfNodePort }}
      {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
