node:
  offlineMode: false
  hydraScriptsTxId: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  extraVolumes:
    - name: cardano-socket
      emptyDir: {}
  extraVolumeMounts:
    - name: cardano-socket
      mountPath: /ipc

keys:
  hydraSigning:
    value: |-
      online-hydra-signing-key
  hydraVerification:
    items:
      - filename: hydra-self.vk
        value: |-
          online-hydra-self-verification-key
      - filename: hydra-peer.vk
        value: |-
          online-hydra-peer-verification-key
  cardano:
    enabled: true
    signing:
      value: |-
        online-cardano-signing-key
    verification:
      value: |-
        online-cardano-verification-key
