name: Check extensions

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/check_extensions.yml"
      - "extensions/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/check_extensions.yml"
      - "extensions/**"

jobs:
  helm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extensions
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: default
            valuesArgs: ""
            dir: midnight
          - name: inline-secrets
            valuesArgs: "-f midnight/ci/values-inline-secrets.yaml"
            dir: midnight
          - name: existing-secrets
            valuesArgs: "-f midnight/ci/values-existing-secrets.yaml"
            dir: midnight
          - name: managed-dbsync
            valuesArgs: "-f midnight/ci/values-managed-dbsync.yaml"
            dir: midnight
          - name: default
            valuesArgs: ""
            dir: cardano-node
          - name: default
            valuesArgs: ""
            dir: control-plane
          - name: default
            valuesArgs: ""
            dir: dolos
          - name: offline-inline
            valuesArgs: "-f hydra-node/ci/values-offline-inline.yaml"
            dir: hydra-node
          - name: offline-existing
            valuesArgs: "-f hydra-node/ci/values-offline-existing.yaml"
            dir: hydra-node
          - name: online-inline
            valuesArgs: "-f hydra-node/ci/values-online-inline.yaml"
            dir: hydra-node
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-amd64.tar.gz -o kubeconform.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform

      - name: Helm lint (${{ matrix.name }} - ${{ matrix.dir }})
        run: helm lint ./${{ matrix.dir }} ${{ matrix.valuesArgs }}

      - name: Template manifests and validate schema (${{ matrix.name }} - ${{ matrix.dir }})
        run: |
          helm template ${{ matrix.dir }} ./${{ matrix.dir }} ${{ matrix.valuesArgs }} | kubeconform -strict -skip PodMonitor,ServiceMonitor,Prometheus -summary -
